name: Node.js E2E Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  TERM: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v3
    - run: yarn
    - run: yarn compile:actions
    - run: yarn test   

